# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dir_listing_gui_qt_v1.ui'
#
# Created: Fri Jun 15 11:47:46 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName(_fromUtf8("dialog"))
        dialog.setWindowModality(QtCore.Qt.NonModal)
        dialog.resize(985, 832)
        dialog.setMouseTracking(True)
        dialog.setAcceptDrops(True)
        #dialog.setModal(False)
        self.tabWidget = QtGui.QTabWidget(dialog)
        self.tabWidget.setGeometry(QtCore.QRect(40, 50, 901, 701))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.dirOnlyTab = QtGui.QWidget()
        self.dirOnlyTab.setAcceptDrops(True)
        self.dirOnlyTab.setObjectName(_fromUtf8("dirOnlyTab"))
        self.scrollArea = QtGui.QScrollArea(self.dirOnlyTab)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setGeometry(QtCore.QRect(30, 290, 841, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.scrollArea.setLineWidth(2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 839, 359))
        self.scrollAreaWidgetContents.setAcceptDrops(True)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.sourcePushButton = QtGui.QPushButton(self.dirOnlyTab)
        self.sourcePushButton.setGeometry(QtCore.QRect(660, 50, 114, 21))
        self.sourcePushButton.setMouseTracking(True)
        self.sourcePushButton.setObjectName(_fromUtf8("sourcePushButton"))
        self.sourceLineEdit = QtGui.QLineEdit(self.dirOnlyTab)
        self.sourceLineEdit.setGeometry(QtCore.QRect(310, 50, 341, 22))
        self.sourceLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.sourceLineEdit.setAutoFillBackground(True)
        self.sourceLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.sourceLineEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.sourceLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.sourceLineEdit.setDragEnabled(True)
        self.sourceLineEdit.setReadOnly(False)
        self.sourceLineEdit.setObjectName(_fromUtf8("sourceLineEdit"))
        self.sourceLabel = QtGui.QLabel(self.dirOnlyTab)
        self.sourceLabel.setGeometry(QtCore.QRect(140, 50, 161, 21))
        self.sourceLabel.setObjectName(_fromUtf8("sourceLabel"))
        self.dirListingFileSaveLineEdit = QtGui.QLineEdit(self.dirOnlyTab)
        self.dirListingFileSaveLineEdit.setGeometry(QtCore.QRect(310, 100, 341, 22))
        self.dirListingFileSaveLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dirListingFileSaveLineEdit.setAutoFillBackground(True)
        self.dirListingFileSaveLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.dirListingFileSaveLineEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.dirListingFileSaveLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.dirListingFileSaveLineEdit.setDragEnabled(True)
        self.dirListingFileSaveLineEdit.setReadOnly(False)
        self.dirListingFileSaveLineEdit.setObjectName(_fromUtf8("dirListingFileSaveLineEdit"))
        self.dirListingFileSavePushButton = QtGui.QPushButton(self.dirOnlyTab)
        self.dirListingFileSavePushButton.setGeometry(QtCore.QRect(660, 100, 114, 21))
        self.dirListingFileSavePushButton.setObjectName(_fromUtf8("dirListingFileSavePushButton"))
        self.dirListingFileSaveLabel = QtGui.QLabel(self.dirOnlyTab)
        self.dirListingFileSaveLabel.setGeometry(QtCore.QRect(10, 100, 291, 21))
        self.dirListingFileSaveLabel.setObjectName(_fromUtf8("dirListingFileSaveLabel"))
        self.addPrefixCheckBox = QtGui.QCheckBox(self.dirOnlyTab)
        self.addPrefixCheckBox.setGeometry(QtCore.QRect(190, 150, 101, 20))
        self.addPrefixCheckBox.setObjectName(_fromUtf8("addPrefixCheckBox"))
        self.prefixLabel = QtGui.QLabel(self.dirOnlyTab)
        self.prefixLabel.setGeometry(QtCore.QRect(340, 150, 62, 21))
        self.prefixLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prefixLabel.setObjectName(_fromUtf8("prefixLabel"))
        self.prefixLineEdit = QtGui.QLineEdit(self.dirOnlyTab)
        self.prefixLineEdit.setEnabled(False)
        self.prefixLineEdit.setGeometry(QtCore.QRect(422, 150, 181, 21))
        self.prefixLineEdit.setObjectName(_fromUtf8("prefixLineEdit"))
        self.createPushButton = QtGui.QPushButton(self.dirOnlyTab)
        self.createPushButton.setGeometry(QtCore.QRect(190, 210, 241, 32))
        self.createPushButton.setAutoDefault(True)
        self.createPushButton.setDefault(False)
        self.createPushButton.setFlat(False)
        self.createPushButton.setObjectName(_fromUtf8("createPushButton"))
        self.clearPushButton = QtGui.QPushButton(self.dirOnlyTab)
        self.clearPushButton.setGeometry(QtCore.QRect(500, 210, 241, 32))
        self.clearPushButton.setObjectName(_fromUtf8("clearPushButton"))
        self.tabWidget.addTab(self.dirOnlyTab, _fromUtf8(""))
        self.dirCheckTab = QtGui.QWidget()
        self.dirCheckTab.setAcceptDrops(True)
        self.dirCheckTab.setObjectName(_fromUtf8("dirCheckTab"))
        self.destLabel = QtGui.QLabel(self.dirCheckTab)
        self.destLabel.setGeometry(QtCore.QRect(20, 60, 281, 21))
        self.destLabel.setObjectName(_fromUtf8("destLabel"))
        self.destPushButton = QtGui.QPushButton(self.dirCheckTab)
        self.destPushButton.setGeometry(QtCore.QRect(660, 60, 114, 21))
        self.destPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.destPushButton.setObjectName(_fromUtf8("destPushButton"))
        self.destLineEdit = QtGui.QLineEdit(self.dirCheckTab)
        self.destLineEdit.setGeometry(QtCore.QRect(310, 60, 341, 22))
        self.destLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.destLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.destLineEdit.setAutoFillBackground(True)
        self.destLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.destLineEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.destLineEdit.setText(_fromUtf8(""))
        self.destLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.destLineEdit.setDragEnabled(True)
        self.destLineEdit.setReadOnly(False)
        self.destLineEdit.setObjectName(_fromUtf8("destLineEdit"))
        self.sourceCheckLineEdit = QtGui.QLineEdit(self.dirCheckTab)
        self.sourceCheckLineEdit.setGeometry(QtCore.QRect(310, 20, 341, 22))
        self.sourceCheckLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.sourceCheckLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sourceCheckLineEdit.setAutoFillBackground(True)
        self.sourceCheckLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.sourceCheckLineEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.sourceCheckLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.sourceCheckLineEdit.setDragEnabled(True)
        self.sourceCheckLineEdit.setReadOnly(False)
        self.sourceCheckLineEdit.setObjectName(_fromUtf8("sourceCheckLineEdit"))
        self.sourceCheckPushButton = QtGui.QPushButton(self.dirCheckTab)
        self.sourceCheckPushButton.setGeometry(QtCore.QRect(660, 20, 114, 21))
        self.sourceCheckPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sourceCheckPushButton.setObjectName(_fromUtf8("sourceCheckPushButton"))
        self.sourceCheckLabel = QtGui.QLabel(self.dirCheckTab)
        self.sourceCheckLabel.setGeometry(QtCore.QRect(10, 20, 291, 21))
        self.sourceCheckLabel.setObjectName(_fromUtf8("sourceCheckLabel"))
        self.clearCheckPushButton = QtGui.QPushButton(self.dirCheckTab)
        self.clearCheckPushButton.setGeometry(QtCore.QRect(500, 210, 241, 32))
        self.clearCheckPushButton.setObjectName(_fromUtf8("clearCheckPushButton"))
        self.prefixCheckLineEdit = QtGui.QLineEdit(self.dirCheckTab)
        self.prefixCheckLineEdit.setEnabled(False)
        self.prefixCheckLineEdit.setGeometry(QtCore.QRect(422, 150, 181, 21))
        self.prefixCheckLineEdit.setObjectName(_fromUtf8("prefixCheckLineEdit"))
        self.addPrefixCheckCheckBox = QtGui.QCheckBox(self.dirCheckTab)
        self.addPrefixCheckCheckBox.setGeometry(QtCore.QRect(190, 150, 101, 20))
        self.addPrefixCheckCheckBox.setObjectName(_fromUtf8("addPrefixCheckCheckBox"))
        self.createCheckPushButton = QtGui.QPushButton(self.dirCheckTab)
        self.createCheckPushButton.setGeometry(QtCore.QRect(190, 210, 241, 32))
        self.createCheckPushButton.setAutoDefault(True)
        self.createCheckPushButton.setDefault(False)
        self.createCheckPushButton.setFlat(False)
        self.createCheckPushButton.setObjectName(_fromUtf8("createCheckPushButton"))
        self.prefixCheckLabel = QtGui.QLabel(self.dirCheckTab)
        self.prefixCheckLabel.setGeometry(QtCore.QRect(340, 150, 62, 21))
        self.prefixCheckLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prefixCheckLabel.setObjectName(_fromUtf8("prefixCheckLabel"))
        self.checkScrollArea = QtGui.QScrollArea(self.dirCheckTab)
        self.checkScrollArea.setEnabled(True)
        self.checkScrollArea.setGeometry(QtCore.QRect(30, 290, 841, 361))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.checkScrollArea.setPalette(palette)
        self.checkScrollArea.setAcceptDrops(False)
        self.checkScrollArea.setAutoFillBackground(False)
        self.checkScrollArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.checkScrollArea.setLineWidth(2)
        self.checkScrollArea.setWidgetResizable(True)
        self.checkScrollArea.setObjectName(_fromUtf8("checkScrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 839, 359))
        self.scrollAreaWidgetContents_2.setAcceptDrops(True)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.checkScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.dirListingCheckFileSaveLabel = QtGui.QLabel(self.dirCheckTab)
        self.dirListingCheckFileSaveLabel.setGeometry(QtCore.QRect(10, 100, 291, 21))
        self.dirListingCheckFileSaveLabel.setObjectName(_fromUtf8("dirListingCheckFileSaveLabel"))
        self.dirListingCheckFileSaveLineEdit = QtGui.QLineEdit(self.dirCheckTab)
        self.dirListingCheckFileSaveLineEdit.setGeometry(QtCore.QRect(310, 100, 341, 22))
        self.dirListingCheckFileSaveLineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.dirListingCheckFileSaveLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dirListingCheckFileSaveLineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.dirListingCheckFileSaveLineEdit.setAutoFillBackground(True)
        self.dirListingCheckFileSaveLineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Australia))
        self.dirListingCheckFileSaveLineEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.dirListingCheckFileSaveLineEdit.setEchoMode(QtGui.QLineEdit.Normal)
        self.dirListingCheckFileSaveLineEdit.setDragEnabled(True)
        self.dirListingCheckFileSaveLineEdit.setReadOnly(False)
        self.dirListingCheckFileSaveLineEdit.setObjectName(_fromUtf8("dirListingCheckFileSaveLineEdit"))
        self.dirListingCheckFileSavePushButton = QtGui.QPushButton(self.dirCheckTab)
        self.dirListingCheckFileSavePushButton.setGeometry(QtCore.QRect(660, 100, 114, 21))
        self.dirListingCheckFileSavePushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.dirListingCheckFileSavePushButton.setObjectName(_fromUtf8("dirListingCheckFileSavePushButton"))
        self.tabWidget.addTab(self.dirCheckTab, _fromUtf8(""))
        self.pushButton = QtGui.QPushButton(dialog)
        self.pushButton.setGeometry(QtCore.QRect(713, 780, 171, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.sourcePushButton.clicked.connect(self.selectSourceDirectory)
        self.dirListingFileSavePushButton.clicked.connect(self.selectDirListingFileSaveDirectory)

        self.addPrefixCheckBox.stateChanged.connect(self.setPrefixLineEdit)

        self.retranslateUi(dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.addPrefixCheckBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.prefixLineEdit.show)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "Directory Listing", None, QtGui.QApplication.UnicodeUTF8))
        self.sourcePushButton.setText(QtGui.QApplication.translate("dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceLabel.setText(QtGui.QApplication.translate("dialog", "Select a Source Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.dirListingFileSavePushButton.setText(QtGui.QApplication.translate("dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.dirListingFileSaveLabel.setText(QtGui.QApplication.translate("dialog", "Select a directory to save directory listing file:", None, QtGui.QApplication.UnicodeUTF8))
        self.addPrefixCheckBox.setText(QtGui.QApplication.translate("dialog", "Add a prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel.setText(QtGui.QApplication.translate("dialog", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.createPushButton.setText(QtGui.QApplication.translate("dialog", "Create Directory Listing", None, QtGui.QApplication.UnicodeUTF8))
        self.clearPushButton.setText(QtGui.QApplication.translate("dialog", "Clear Display", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dirOnlyTab), QtGui.QApplication.translate("dialog", "Directory Listing", None, QtGui.QApplication.UnicodeUTF8))
        self.destLabel.setText(QtGui.QApplication.translate("dialog", "Select the directory the files were copied to:", None, QtGui.QApplication.UnicodeUTF8))
        self.destPushButton.setText(QtGui.QApplication.translate("dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceCheckPushButton.setText(QtGui.QApplication.translate("dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.sourceCheckLabel.setText(QtGui.QApplication.translate("dialog", "Select directory where files were copied from:", None, QtGui.QApplication.UnicodeUTF8))
        self.clearCheckPushButton.setText(QtGui.QApplication.translate("dialog", "Clear Display", None, QtGui.QApplication.UnicodeUTF8))
        self.addPrefixCheckCheckBox.setText(QtGui.QApplication.translate("dialog", "Add a prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.createCheckPushButton.setText(QtGui.QApplication.translate("dialog", "Create Directory Listing", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixCheckLabel.setText(QtGui.QApplication.translate("dialog", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.dirListingCheckFileSaveLabel.setText(QtGui.QApplication.translate("dialog", "Select a directory to save directory listing file:", None, QtGui.QApplication.UnicodeUTF8))
        self.dirListingCheckFileSavePushButton.setText(QtGui.QApplication.translate("dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dirCheckTab), QtGui.QApplication.translate("dialog", "Directory Listing and Check", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))

    def selectSourceDirectory(self):
      self.sourceLineEdit.setText(QtGui.QFileDialog.getExistingDirectory())

    def selectDirListingFileSaveDirectory(self):
      self.dirListingFileSaveLineEdit.setText(QtGui.QFileDialog.getExistingDirectory())

    def setPrefixLineEdit(self):
      if self.prefixLineEdit.isEnabled():
        self.prefixLineEdit.setEnabled(False)
      else:
        self.prefixLineEdit.setEnabled(True)

    def selectDirListingCheckFileSaveDirectory(self):
      self.dirListingCheckFileSaveLineEdit.setText(QtGui.QFileDialog.getExistingDirectory())

    def selectSourceCheckDirectory(self):
      self.sourceCheckLineEdit.setText(QtGui.QFileDialog.getExistingDirectory())

    def selectDestDirectory(self):
      self.destLineEdit.setText(QtGui.QFileDialog.getExistingDirectory())

    def setPrefixLineEdit(self):
      if self.prefixLineEdit.isEnabled():
        self.prefixLineEdit.setEnabled(False)
      else:
        self.prefixLineEdit.setEnabled(True)
